POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "username": "testuser3",
  "password": "testpassword3",
  "email": "test3@example.com"
}
###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "testuser1",
  "password": "testpassword1"
}
###
POST /user/subscribeUserToBook HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJpc3MiOiJTcHJpbmdCb290QXBwbGljYXRpb24iLCJleHAiOjE3NDQyMzk2MTUsImlhdCI6MTc0NDIzNjAxNSwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEifQ.Ww_NUI0EKnhOL9r0a_3CsxZuSFnEjgkDGjcFPPy6_7E
Content-Type: application/json

{
  "userName": "testuser1",
  "bookName": "Преступление и наказание"
}
###
POST /genre/getBookGenre HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJpc3MiOiJTcHJpbmdCb290QXBwbGljYXRpb24iLCJleHAiOjE3NDQyNTM4NTUsImlhdCI6MTc0NDI1MDI1NSwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEifQ.4EalFt8yIRIOkVYhuJkvtPvPmPTNXQFjao4ld9V4iqM
Content-Type: application/json

{
  "bookName": "Преступление и наказание"
}
###
POST /books/showRecommendBooks HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJpc3MiOiJTcHJpbmdCb290QXBwbGljYXRpb24iLCJleHAiOjE3NDQyNTM4NTUsImlhdCI6MTc0NDI1MDI1NSwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEifQ.4EalFt8yIRIOkVYhuJkvtPvPmPTNXQFjao4ld9V4iqM
Content-Type: application/json

["Роман", "Триллер"]
###
GET http://localhost:8080/chapters/1/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJpc3MiOiJTcHJpbmdCb290QXBwbGljYXRpb24iLCJleHAiOjE3MzM1MjIyMjIsImlhdCI6MTczMzUxODYyMiwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEifQ.PhbwJwnBXSBckJmwAalrAngxBKsEJ2CRhCAS_xzoKSY
###
GET http://localhost:8080/books/1/voices
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJpc3MiOiJTcHJpbmdCb290QXBwbGljYXRpb24iLCJleHAiOjE3MzM1ODIzOTUsImlhdCI6MTczMzU3ODc5NSwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEifQ.nuJaUgMc1Kd7y3C2XProPoc3nXw2QUpqQxwrTv9YjXo
###
GET http://localhost:8080/showUserInfo
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJpc3MiOiJTcHJpbmdCb290QXBwbGljYXRpb24iLCJleHAiOjE3MzM0OTcwNTAsImlhdCI6MTczMzQ5MzQ1MCwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEifQ._C9ZIBBkUqYNy1Ps1KALCa_vk2rdMF59UykW9oec1Bc
###
GET http://localhost:8080/books/show
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJpc3MiOiJTcHJpbmdCb290QXBwbGljYXRpb24iLCJleHAiOjE3NDQyMzk2MTUsImlhdCI6MTc0NDIzNjAxNSwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEifQ.Ww_NUI0EKnhOL9r0a_3CsxZuSFnEjgkDGjcFPPy6_7E